name: Github Actions Demo
on: push
jobs:
    check-os-version:
        runs-on: ubuntu-latest
        steps:
            - run: uname -v
    run-python-program:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: python3 hello.py